# Rustfmt configuration (stable options only)
# See: https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
fn_call_width = 60
attr_fn_like_width = 70
struct_lit_width = 18
struct_variant_width = 35
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
short_array_element_width_threshold = 10
match_block_trailing_comma = false
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
fn_params_layout = "Tall"
match_arm_leading_pipes = "Never"

# Note: Many options require nightly rustfmt with unstable_features = true
# For full list, see: https://rust-lang.github.io/rustfmt/
